CREATE TABLE `{prefix}_bannerclient` (
  `cid` int(11) NOT NULL auto_increment,
  `name` varchar(60) NOT NULL default '',
  `contact` varchar(60) default NULL,
  `email` varchar(191) NOT NULL default '',
  `tel` varchar(50) default NULL,
  `address1` varchar(191) default NULL,
  `address2` varchar(191) default NULL,
  `city` varchar(100) default NULL,
  `region` varchar(100) default NULL,
  `postal_code` varchar(20) default NULL,
  `country_code` varchar(2) default NULL,
  `login` varchar(25) NOT NULL default '',
  `passwd` varchar(255) NOT NULL default '',
  `extrainfo` text,
  `status` tinyint(1) NOT NULL default '1',
  `date_created` int(10) unsigned NOT NULL default '0',
  `last_updated` int(10) unsigned NOT NULL default '0',
  PRIMARY KEY  (`cid`),
  UNIQUE KEY `login` (`login`)
) ENGINE=InnoDB;

CREATE TABLE `{prefix}_banner` (
  `bid` int(11) NOT NULL auto_increment,
  `cid` int(11) NOT NULL default '0',
  `campaign_id` int(11) default NULL,
  `name` varchar(100) default NULL,
  `banner_type` varchar(20) NOT NULL default 'image',
  `imageurl` varchar(191) default NULL,
  `clickurl` varchar(191) default NULL,
  `htmlbanner` tinyint(1) NOT NULL default '0',
  `htmlcode` text,
  `width` int(11) default NULL,
  `height` int(11) default NULL,
  `imptotal` int(11) NOT NULL default '0',
  `impmade` int(11) NOT NULL default '0',
  `clicks` int(11) NOT NULL default '0',
  `start_date` datetime default NULL,
  `end_date` datetime default NULL,
  `timezone` varchar(50) default NULL,
  `date_created` int(10) unsigned NOT NULL default '0',
  `last_impression_time` datetime default NULL,
  `last_click_time` datetime default NULL,
  `status` tinyint(1) NOT NULL default '1',
  `weight` int(5) NOT NULL default '10',
  PRIMARY KEY  (`bid`),
  KEY `cid` (`cid`),
  KEY `status_dates` (`status`, `start_date`, `end_date`)
) ENGINE=InnoDB;

CREATE TABLE `{prefix}_bannerfinish` (
  `bid` int(11) NOT NULL,
  `cid` int(11) NOT NULL default '0',
  `campaign_id` int(11) default NULL,
  `name` varchar(100) default NULL,
  `banner_type` varchar(20) NOT NULL default 'image',
  `imageurl` varchar(191) default NULL,
  `clickurl` varchar(191) default NULL,
  `htmlcode` text,
  `width` int(11) default NULL,
  `height` int(11) default NULL,
  `imptotal_allocated` int(11) NOT NULL default '0',
  `impressions_made` int(11) NOT NULL default '0',
  `clicks_made` int(11) NOT NULL default '0',
  `datestart_original` datetime default NULL,
  `dateend_original` datetime default NULL,
  `timezone_original` varchar(50) default NULL,
  `date_created_original` int(10) unsigned NOT NULL default '0',
  `date_finished` int(10) unsigned NOT NULL default '0',
  `finish_reason` varchar(50) default NULL,
  PRIMARY KEY  (`bid`),
  KEY `cid` (`cid`),
  KEY `date_finished` (`date_finished`)
) ENGINE=InnoDB;
